### PR TITLE
Upgrade to version 14.4.4

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 14.4.4
- New permissions

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@Gofannon sorry I pushed this PR before realising that you pushed a similar one...

**Review by Gofannon — APPROVED** [review]
LGTM

**Comment by Gofannon** [comment]
@ericgaspar no worries :) I'm not that active anyways here

**Pull request merged**
